{{- if and .Values.config .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
{{- range $k, $v := .Values.config.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
