{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name | default .Chart.Name }}
  labels:
{{- if .Values.app.labels }}
{{ toYaml .Values.app.labels | nindent 4 }}
{{- else }}
    app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name }}
{{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{- if .Values.app.labels }}
{{ toYaml .Values.app.labels | nindent 6 }}
{{- else }}
      app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name }}
{{- end }}
  endpoints:
    - port: {{ .Values.service.portName | default "web" }}
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
{{- end }}
