mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.111.0   
  pullPolicy: IfNotPresent
config:
  receivers:
    otlp:
      protocols:
        http:
        grpc:
  processors:
    batch: {}
    resource:
      attributes:
        - key: service.namespace
          action: upsert
          value: "local-dev"
  exporters:
    otlp/tempo:
      endpoint: tempo.tracing.svc.cluster.local:4317
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [otlp/tempo]
