name: Deploy to kind (local)

on:
  push:
    branches: [ main ]
    paths:
      - "i-am-doing-all-helm/**"   # נפרוס רק כשערכי ההלם השתנו

jobs:
  deploy:
    runs-on: [self-hosted, kind]  # ה-runner שלך במחשב, עם label "kind"
    permissions:
      contents: read
      packages: read              # למשיכת אימג' מ-GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read image & tag from values-dev.yaml
        id: vals
        shell: bash
        run: |
          FILE="i-am-doing-all-helm/wifee/values-dev.yaml"
          IMG=$(grep -E '^[[:space:]]*repository:' -m1 "$FILE" | awk '{print $2}')
          TAG=$(grep -E '^[[:space:]]*tag:' -m1 "$FILE" | sed -E 's/^[^"]*"?([^"]+).*/\1/')
          echo "img=$IMG" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Pull image and load into kind
        shell: bash
        run: |
          set -e
          FULL="${{ steps.vals.outputs.img }}:${{ steps.vals.outputs.tag }}"
          echo "Pulling $FULL and loading to kind..."
          docker pull "$FULL"
          kind load docker-image "$FULL" --name dev   # אם הקלאסטר נקרא dev
        # kind load docker-image → טעינה ישירה לצמתים (לא מצריך imagePullSecret)
        # ר' התיעוד  :contentReference[oaicite:7]{index=7}

      - name: Helm upgrade on local kind
        shell: bash
        run: |
          cd i-am-doing-all-helm/wifee
          helm dependency update
          helm upgrade --install wifee . -f values-dev.yaml --namespace default
