app:
  name: wifee
  port: 5000
  # labels:
  #   app.kubernetes.io/name: wifee
  #   app.kubernetes.io/instance: wifee


deployment:
  replicas: 1 
  image:
    repository: ghcr.io/davidshandor/wifee
    tag: "1.0.12"
    pullPolicy: IfNotPresent

service:
  name: wifee     
  type: ClusterIP
  port: 80
  portName: web

serviceMonitor:
  enabled: true
  interval: 15s
  path: /metrics
  

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: local.wifee
      paths:
        - path: /
          pathType: Prefix
  tls: []   # כשתרצה TLS: ספק רשומות עם secretName+hosts

mongodb:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    rootUser: root
    rootPassword: devpass
  persistence:
    enabled: false


certManager:
  enabled: false
  issuerName: cluster-issuer-prod
  issuerKind: ClusterIssuer

secrets:
  enabled: true
  name: wifee-secret
  data:
    MONGO_URI: "mongodb://root:devpass@wifee-mongodb:27017/wife_todo_list?authSource=admin"
    
config:
  enabled: true
  name: wifee-conf
  data:
    LOG_LEVEL: "info"

env:
  - name: REDIS_HOST
    value: redis-master.data.svc.cluster.local
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password
  - name: OTEL_SERVICE_NAME
    value: api
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: deployment.environment=dev,service.version=1.0.0
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://otel-collector.otel:4318