name: CI
permissions:
  packages: write
  contents: write

on:
  push:
    branches: [ main, "**" ]
    paths:
      - "i-am-doing-all/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "i-am-doing-all/**"

env:
  IMAGE_NAME: wifee
  BASE_VERSION: "1.0"

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # ↓↓↓ יצירת owner/image באותיות קטנות
      - name: Normalize image coordinates (lowercase)
        shell: bash
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "IMAGE_LC=${IMAGE_NAME,,}" >> $GITHUB_ENV
          echo "IMG=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Compute image tag (1.0.x)
        id: ver
        shell: bash
        run: |
          git fetch --tags --force
          LAST=$(git tag --list "${BASE_VERSION}.*" --sort=-v:refname | head -n1 || true)
          if [ -z "$LAST" ]; then PATCH=0; else PATCH=$(echo "$LAST" | awk -F. '{print $3+1}'); fi
          echo "TAG=${BASE_VERSION}.${PATCH}" >> $GITHUB_ENV
          echo "tag=${BASE_VERSION}.${PATCH}" >> $GITHUB_OUTPUT
          echo "Computed tag: ${BASE_VERSION}.${PATCH}"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: ./i-am-doing-all
          push: true
          tags: ${{ env.IMG }}:${{ steps.ver.outputs.tag }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - name: Create & push git tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.email "github-actions@users.noreply.github.com"
          git config user.name  "github-actions"
          git tag -a "${TAG}" -m "version ${TAG}" || true
          git push origin "${TAG}" || true

      - name: Bump image repo+tag in Helm values (monorepo)
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          set -e
          IMG="${IMG}"   # כבר באותיות קטנות מהשלב למעלה
          for f in i-am-doing-all-helm/wifee/values.yaml i-am-doing-all-helm/wifee/values-dev.yaml; do
            if [ -f "$f" ]; then
              sed -i -E "s|(^[[:space:]]*repository:[[:space:]]*).*$|\\1${IMG}|" "$f" || true
              sed -i -E "s|(^[[:space:]]*tag:[[:space:]]*).*$|\\1\"${TAG}\"|" "$f" || true
            fi
          done
          git add i-am-doing-all-helm/wifee/*.yaml
          git commit -m "chore(helm): bump image to ${TAG}" || echo "no changes"
          git push

    outputs:
      tag:   ${{ steps.ver.outputs.tag }}
      image: ${{ env.IMG }}
