name: Deploy to kind (local)

on:
  workflow_run:
    workflows: ["CI"]          # השם של ה-CI שלך
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Windows, X64, wife-kind]   # ← תואם את ה-label שבראנר
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repo at the CI commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read image & tag from values-dev.yaml
        id: vals
        shell: bash
        run: |
          FILE="i-am-doing-all-helm/wifee/values-dev.yaml"
          IMG=$(grep -E '^[[:space:]]*repository:' -m1 "$FILE" | awk '{print $2}')
          TAG=$(grep -E '^[[:space:]]*tag:' -m1 "$FILE" | sed -E 's/^[^"]*"?([^"]+).*/\1/')
          echo "img=$IMG" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using $IMG:$TAG"

      - name: Pull image and load to kind
        shell: bash
        run: |
          FULL="${{ steps.vals.outputs.img }}:${{ steps.vals.outputs.tag }}"
          docker pull "$FULL"
          kind load docker-image "$FULL" --name dev   # אם הקלאסטר שלך נקרא dev

      - name: Helm upgrade (local kind)
        shell: bash
        run: |
          cd i-am-doing-all-helm/wifee
          helm dependency update
          helm upgrade --install wifee . -f values-dev.yaml --namespace default
