name: Deploy to kind (local)

on:
  workflow_run:
    workflows: ["CI"]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Windows, X64, wife-kind]
    defaults:
      run:
        shell: 'powershell -NoProfile -ExecutionPolicy Bypass -File {0}'
    permissions:
      contents: read
    steps:
      - name: Checkout repo at the CI commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Read image & tag from values-dev.yaml
        id: vals
        run: |
          $FILE = "i-am-doing-all-helm/wifee/values-dev.yaml"
          $c = Get-Content -Raw $FILE
          $img = [regex]::Match($c,'(?m)^\s*repository:\s*(.+)$').Groups[1].Value.Trim()
          $tag = [regex]::Match($c,'(?m)^\s*tag:\s*"?([^"#]+)"?').Groups[1].Value.Trim()
          "img=$img" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "tag=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          Write-Host ("Using {0}:{1}" -f $img, $tag)

      # <<< חשוב: לייצא kubeconfig של kind ולהשתמש בו >>>
      - name: Prepare kubeconfig for kind (dev)
        run: |
          kind get clusters
          kind export kubeconfig --name dev --kubeconfig "$env:RUNNER_TEMP\kubeconfig"
          "KUBECONFIG=$env:RUNNER_TEMP\kubeconfig" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          kubectl config current-context
          kubectl cluster-info

      - name: Helm upgrade (local kind)
        run: |
          Set-Location i-am-doing-all-helm/wifee
          helm dependency update
          helm upgrade --install wifee . -f values-dev.yaml `
            --namespace default `
            --set image.pullPolicy=Always

      - name: Show pods
        run: kubectl get pods -n default -o wide
