name: Deploy to kind (local)

on:
  workflow_run:
    workflows: ["CI"]          # השם של ה-CI שלך
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Windows, X64, wife-kind]   # ← תואם את ה-label שבראנר
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repo at the CI commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read image & tag from values-dev.yaml
        id: vals
        shell: powershell
        run: |
          $FILE = "i-am-doing-all-helm/wifee/values-dev.yaml"
          $content = Get-Content $FILE

          $imgLine = ($content | Where-Object { $_ -match '^\s*repository:\s*' } | Select-Object -First 1)
          $tagLine = ($content | Where-Object { $_ -match '^\s*tag:\s*' }        | Select-Object -First 1)

          $img = [regex]::Match($imgLine, '^\s*repository:\s*(.+)$').Groups[1].Value.Trim()
          $tag = [regex]::Match($tagLine, '^\s*tag:\s*"?([^"]+)"?').Groups[1].Value.Trim()

          "img=$img" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "tag=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "Using $img:$tag"

      - name: Pull image and load to kind
        shell: powershell
        run: |
          $full = "${{ steps.vals.outputs.img }}:${{ steps.vals.outputs.tag }}"
          docker pull $full
          kind load docker-image $full --name dev

      - name: Helm upgrade (local kind)
        shell: powershell
        run: |
          Set-Location i-am-doing-all-helm/wifee
          helm dependency update
          helm upgrade --install wifee . -f values-dev.yaml --namespace default
